version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "8080:80"
    volumes:
      - ./nginx-html:/usr/share/nginx/html:ro
    restart: always
